package com.devleonore.dragonicworm.template

import com.devleonore.dragonicworm.model.ProjectConfig

object ReadmeGenerator {

    fun generate(cfg: ProjectConfig): String {
        val mainFile = if (cfg.language.label == "Python") "main.py" else "main.sh"
        val structureExtra = if (cfg.language.label == "Python")
            "requirements.txt\n├── modules/\n├── assets/\n└── config/"
        else
            "config/\n├── modules/\n└── assets/"

        val features = if (cfg.menuItems.isNotEmpty() && cfg.template.usesMenu) {
            cfg.menuItems.joinToString("\n") { "- ${it.name.ifBlank { "Feature" }}" }
        } else {
            "- Core functionality"
        }

        val authorSlug = cfg.author.replace(Regex("\\s+"), "")
        val outputName = cfg.resolvedOutputName()

        return """
            |# ${cfg.projectName}
            |
            |> ${cfg.description.ifBlank { "A Termux tool." }}
            |
            |---
            |
            |## 📋 Information
            |
            || Field       | Value              |
            ||-------------|--------------------|
            || **Name**    | ${cfg.projectName} |
            || **Author**  | ${cfg.author}      |
            || **Version** | ${cfg.version}     |
            || **License** | ${cfg.license}     |
            || **Language**| ${cfg.language.label}    |
            |
            |---
            |
            |## 🚀 Installation
            |
            |```bash
            |# Clone the project
            |git clone https://github.com/$authorSlug/$outputName
            |
            |# Navigate to folder
            |cd ${cfg.outputFolder.ifBlank { outputName }}
            |
            |# Run installer
            |bash install.sh
            |```
            |
            |---
            |
            |## 💻 Usage
            |
            |```bash
            |bash run.sh
            |```
            |
            |---
            |
            |## 📦 Dependencies
            |
            |${if (cfg.language.label == "Python") "### Python Packages\n```\n${cfg.depPip.ifBlank { "None" }}\n```" else ""}
            |### System Packages
            |```
            |${cfg.depPkg.ifBlank { "None" }}
            |```
            |
            |---
            |
            |## 🧩 Features
            |
            |$features
            |
            |---
            |
            |## 📁 Structure
            |
            |```
            |$outputName/
            |├── $mainFile
            |├── install.sh
            |├── run.sh
            |├── README.md
            |├── LICENSE
            |├── $structureExtra
            |```
            |
            |---
            |
            |## 👤 Author
            |
            |**${cfg.author}**
            |
            |---
            |
            |*Generated by DRAGONIC WORM BUILDER — Developed by Dev Leonore*
        """.trimMargin()
    }
}
